system:
  localization_method: fingerprinting
  rolling_average_window: 5
  signal_filter:
    noise_floor_dbm: -80
    min_aps_for_localization: 3
  max_distance_for_high_confidence_m: 3.0
  boundary_clamp_margin_m: 0.01
  consensus_threshold: 0.8
  frame_window_minutes: 1
  testing_mode: false
  methods:
  - trilateration
telemetry_config:
  edge_campus_id: Carleton University
  edge_building_id: Canal Building
  edge_floor_id: '1'
  poll_interval_s: 1.5
  update_interval_s: 60
  prompts:
    main: eap350>
    sub: eap350/wless2/network>
  default_ap_credentials:
    username: admin
    password: admin
targets:
- ssid: Tag2
  radio_override:
    rssi_at_1m_dbm: -22.0
    path_loss_n: 4.0
- ssid: Tag3
  radio_override:
    rssi_at_1m_dbm: -22.0
    path_loss_n: 3.0
- ssid: Tag2
  radio_override:
    rssi_at_1m_dbm: -22.0
    path_loss_n: 3.0
- ssid: TOF_TAG_0
  radio_override:
    rssi_at_1m_dbm: -22.0
    path_loss_n: 3.0
- ssid: Tag1
  radio_override:
    rssi_at_1m_dbm: -22.0
    path_loss_n: 3.0
locations:
  Carleton University:
    buildings:
      Canal Building:
        floors:
          '1':
            width_m: 37.699
            height_m: 49.049
            wifi_aps:
              WAP6:
                host: 192.168.1.54
                x: 16.92
                y: 9.42
                username: admin
                password: admin
              WAP4:
                host: 192.168.1.22
                x: 29.55
                y: 19.14
                username: admin
                password: admin
              WAP1:
                host: 192.168.1.75
                x: 9.88
                y: 16.82
                username: admin
                password: admin
              WAP10:
                host: 192.168.1.19
                x: 16.1
                y: 43.41
                username: admin
                password: admin
            tof_anchors: {}
            rooms:
              Lobby:
                center_x: 11.484
                center_y: 39.211
                polygon:
                - - 9.61
                  - 24.25
                - - 18.21
                  - 24.25
                - - 18.09
                  - 37.08
                - - 19.17
                  - 37.14
                - - 19.19
                  - 43.49
                - - 11.92
                  - 43.47
                - - 11.95
                  - 47.75
                - - 9.58
                  - 47.77
                - - 9.62
                  - 44.64
                - - 8.78
                  - 44.66
                - - 8.76
                  - 40.8
                - - 3.13
                  - 40.81
                - - 3.17
                  - 36.42
                - - 9.6
                  - 36.42
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Hall 1:
                center_x: 11.924
                center_y: 17.352
                polygon:
                - - 9.62
                  - 11.11
                - - 12.01
                  - 11.14
                - - 11.99
                  - 15.71
                - - 14.05
                  - 15.75
                - - 14.05
                  - 18.29
                - - 12.03
                  - 18.29
                - - 12.03
                  - 24.28
                - - 9.61
                  - 24.25
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Hall 2:
                center_x: 19.517
                center_y: 10.707
                polygon:
                - - 9.01
                  - 9.34
                - - 9.01
                  - 11.11
                - - 9.62
                  - 11.11
                - - 12.01
                  - 11.14
                - - 20.72
                  - 11.12
                - - 26.97
                  - 13.63
                - - 27.63
                  - 15.71
                - - 27.63
                  - 9.31
                - - 26.8
                  - 9.31
                - - 26.8
                  - 8.68
                - - 19
                  - 8.68
                - - 19
                  - 9.34
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Hall 4:
                center_x: 28.135
                center_y: 15.369
                polygon:
                - - 27.62
                  - 5.97
                - - 29.67
                  - 5.94
                - - 29.69
                  - 23.81
                - - 27.07
                  - 23.87
                - - 27.86
                  - 21.61
                - - 27.91
                  - 16.73
                - - 27.63
                  - 15.71
                - - 27.63
                  - 9.31
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Hall 3:
                center_x: 24.413
                center_y: 24.621
                polygon:
                - - 18.21
                  - 24.25
                - - 18.12
                  - 26.56
                - - 30.24
                  - 26.56
                - - 30.43
                  - 23.8
                - - 29.69
                  - 23.81
                - - 27.07
                  - 23.87
                - - 20.78
                  - 23.84
                - - 20.76
                  - 24.28
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Exit 1:
                center_x: 20.796
                center_y: 41.129
                polygon:
                - - 19.19
                  - 36.33
                - - 23.18
                  - 36.32
                - - 23.18
                  - 44.16
                - - 21.53
                  - 44.15
                - - 21.4
                  - 43.74
                - - 19.53
                  - 43.7
                - - 19.19
                  - 43.49
                - - 19.17
                  - 37.14
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Exit 2:
                center_x: 1.583
                center_y: 39.182
                polygon:
                - - 0.04
                  - 37.55
                - - 3.14
                  - 37.58
                - - 3.13
                  - 40.81
                - - 0.02
                  - 40.79
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Cha Time:
                center_x: 4.144
                center_y: 42.33
                polygon:
                - - 0.02
                  - 40.79
                - - 3.13
                  - 40.81
                - - 8.76
                  - 40.8
                - - 8.78
                  - 44.66
                - - 0.03
                  - 44.59
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Stair 2A:
                center_x: 14.538
                center_y: 47.362
                polygon:
                - - 11.97
                  - 45.5
                - - 18.39
                  - 45.52
                - - 18.4
                  - 49.01
                - - 11.98
                  - 49.03
                - - 11.95
                  - 47.75
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Aerospace Lab:
                center_x: 6.957
                center_y: 33.958
                polygon:
                - - 4.33
                  - 31.5
                - - 9.59
                  - 31.52
                - - 9.6
                  - 36.42
                - - 4.31
                  - 36.39
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Breakout Room:
                center_x: 7.478
                center_y: 29.672
                polygon:
                - - 5.37
                  - 27.83
                - - 9.63
                  - 27.83
                - - 9.59
                  - 31.52
                - - 5.32
                  - 31.51
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Lecture Room:
                center_x: 7.065
                center_y: 14.062
                polygon:
                - - 9.01
                  - 9.34
                - - 2.58
                  - 9.3
                - - 2.58
                  - 21.74
                - - 9.59
                  - 21.77
                - - 9.62
                  - 11.11
                - - 9.01
                  - 11.11
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Lecture Room 3:
                center_x: 23.085
                center_y: 18.963
                polygon:
                - - 18.33
                  - 11.1
                - - 20.72
                  - 11.12
                - - 26.97
                  - 13.63
                - - 27.63
                  - 15.71
                - - 27.91
                  - 16.73
                - - 27.86
                  - 21.61
                - - 27.07
                  - 23.87
                - - 20.78
                  - 23.84
                - - 19.16
                  - 23.86
                - - 19.16
                  - 23.56
                - - 18.35
                  - 23.56
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Breakout Room 2302:
                center_x: 33.502
                center_y: 25.582
                polygon:
                - - 30.43
                  - 23.8
                - - 36.57
                  - 23.86
                - - 36.58
                  - 27.33
                - - 30.43
                  - 27.34
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Lab:
                center_x: 33.682
                center_y: 16.43
                polygon:
                - - 29.72
                  - 9
                - - 37.62
                  - 9.05
                - - 37.699
                  - 23.86
                - - 29.69
                  - 23.81
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Stair 2B:
                center_x: 32.877
                center_y: 7.475
                polygon:
                - - 29.67
                  - 5.94
                - - 36.05
                  - 5.95
                - - 36.07
                  - 9.01
                - - 29.72
                  - 9
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Storage:
                center_x: 29.635
                center_y: 4.43
                polygon:
                - - 27.63
                  - 2.9
                - - 31.62
                  - 2.9
                - - 31.67
                  - 5.95
                - - 27.62
                  - 5.97
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Lecture Room 2:
                center_x: 23.268
                center_y: 6.35
                polygon:
                - - 15.33
                  - 0.01
                - - 27.57
                  - 0.01
                - - 27.63
                  - 2.9
                - - 27.62
                  - 5.97
                - - 27.63
                  - 9.31
                - - 26.8
                  - 9.31
                - - 26.8
                  - 8.68
                - - 19
                  - 8.68
                - - 19
                  - 9.34
                - - 15.3
                  - 9.29
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
              Privacy Zone:
                center_x: 14.561
                center_y: 18.041
                polygon:
                - - 12.01
                  - 11.14
                - - 18.33
                  - 11.1
                - - 18.35
                  - 23.56
                - - 18.21
                  - 24.25
                - - 12.03
                  - 24.28
                - - 12.03
                  - 18.29
                - - 14.05
                  - 18.29
                - - 14.05
                  - 15.75
                - - 11.99
                  - 15.71
                priority_label: Standard
                localization_type: rssi_section
                alert_on_exit: false
mqtt:
  broker_host: localhost
  broker_port: 1883
  topic_prefix: capstone
  keepalive_s: 60
cloud:
  s3_key_template: '{campus}_{building}_{floor}_latest.json'
  s3_cache_control: max-age=2
  radiomap_path: radiomap_{campus}_{building}_{floor}.json
  csv_trilat_log_path: trilat_log.csv
  csv_finger_log_path: finger_log.csv
  csv_gp_log_path: gp_log.csv
  csv_ble_log_path: ble_log.csv
  csv_tof_log_path: tof_log.csv
