// =============================================================================
// tag_main.c  --  ESP32-S3  FTM Thin-Client Tag  (MQTT raw-range publisher)
// =============================================================================
//
// This tag:
//   1. Starts in AP+STA mode (AP as FTM responder for anchors, STA for MQTT)
//   2. Scans for TOF_ANCHOR_* SSIDs
//   3. Initiates FTM ranging to each discovered anchor
//   4. Publishes raw per-anchor range measurements as JSON to MQTT
//
// All positioning math (trilateration, GP, fusion) is performed server-side
// by the Hybrid engine. The tag is a thin data source only.
//
// JSON payload (one message per anchor ranged):
//   {
//     "device_id":   "tag_0",
//     "target_id":   "anchor_61",
//     "distance_m":  2.50,
//     "rtt_ps":      166667,
//     "rssi":        -65,
//     "confidence":  0.85,
//     "scan_number": 42,
//     "uptime_ms":   123456
//   }
//
// =============================================================================

#include <string.h>
#include <stdio.h>
#include <math.h>
#include <inttypes.h>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"

#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_log.h"
#include "esp_netif.h"
#include "esp_mac.h"
#include "esp_timer.h"
#include "esp_system.h"
#include "nvs_flash.h"
#include "lwip/ip4_addr.h"
#include "mqtt_client.h"

// -----------------------------------------------------------------------------
//  Per-device config -- auto-generated by platform backend (esp_flash.py)
//  Falls back to defaults if the header does not exist yet.
// -----------------------------------------------------------------------------
#if __has_include("device_config.h")
    #include "device_config.h"
#else
    #warning "device_config.h not found -- using built-in defaults"
    #define TAG_NUM             0
    #define DEVICE_ID           "tag_0"
    #define LOCATION_ID         "lab_1"
    #define FLOOR_ID            "floor_1"
    #define WIFI_STA_SSID       "EAP1250"
    #define WIFI_STA_PASS       ""
    #define MQTT_BROKER_URI     "mqtt://192.168.100.10:1883"
    #define TAG_AP_CHANNEL      1
    #define TAG_AP_IP_LAST      100
#endif

// Fixed settings (same across all tags)
#define TAG_AP_MAX_CONN     4
#define MAX_ANCHORS         6
#define SCAN_INTERVAL_MS    2000
#define FTM_FRAME_COUNT     16
#define FTM_BURST_PERIOD    2
#define WIFI_RETRY_MAX      10

// MQTT topic prefix -- matches engine MQTTPipe subscription
#define MQTT_TOPIC_PREFIX   "capstone/tof/tag"

// -----------------------------------------------------------------------------
//  Globals
// -----------------------------------------------------------------------------
static const char *TAG = "TAG";
static char s_tag_ap_ssid[32];
static int  s_scan_number = 0;
static int  s_retry_num   = 0;

// Wi-Fi
static EventGroupHandle_t s_wifi_event_group;
#define WIFI_CONNECTED_BIT  BIT0
#define WIFI_FAIL_BIT       BIT1
#define FTM_DONE_BIT        BIT2
#define FTM_FAILED_BIT      BIT3

// MQTT
static esp_mqtt_client_handle_t s_mqtt_client = NULL;
static bool s_mqtt_connected = false;

// FTM
static uint32_t s_rtt_ps = 0;

typedef struct {
    char     ssid[32];
    uint8_t  bssid[6];
    int      anchor_id;
    uint8_t  channel;
    uint32_t rtt_ps;
    float    distance_cm;
    int8_t   rssi;
    bool     valid;
    bool     ftm_done;
} anchor_info_t;

static anchor_info_t s_anchors[MAX_ANCHORS];
static int           s_anchor_count = 0;

// -----------------------------------------------------------------------------
//  Wi-Fi + FTM Event Handler
// -----------------------------------------------------------------------------
static void wifi_event_handler(void *arg, esp_event_base_t event_base,
                               int32_t event_id, void *event_data)
{
    if (event_base == WIFI_EVENT) {
        switch (event_id) {

        case WIFI_EVENT_STA_START:
            esp_wifi_connect();
            ESP_LOGI(TAG, "STA started, connecting to %s...", WIFI_STA_SSID);
            break;

        case WIFI_EVENT_STA_DISCONNECTED:
            if (s_retry_num < WIFI_RETRY_MAX) {
                esp_wifi_connect();
                s_retry_num++;
                ESP_LOGW(TAG, "STA disconnected, retry %d/%d",
                         s_retry_num, WIFI_RETRY_MAX);
            } else {
                xEventGroupSetBits(s_wifi_event_group, WIFI_FAIL_BIT);
                ESP_LOGE(TAG, "STA failed after %d retries", WIFI_RETRY_MAX);
            }
            break;

        case WIFI_EVENT_AP_STACONNECTED: {
            wifi_event_ap_staconnected_t *e = event_data;
            ESP_LOGI(TAG, "AP: device " MACSTR " connected", MAC2STR(e->mac));
            break;
        }

        case WIFI_EVENT_AP_STADISCONNECTED: {
            wifi_event_ap_stadisconnected_t *e = event_data;
            ESP_LOGI(TAG, "AP: device " MACSTR " disconnected", MAC2STR(e->mac));
            break;
        }

        case WIFI_EVENT_FTM_REPORT: {
            wifi_event_ftm_report_t *report = event_data;

            if (report->status == FTM_STATUS_SUCCESS) {
                uint8_t num = report->ftm_report_num_entries;
                wifi_ftm_report_entry_t *entries = malloc(
                    sizeof(wifi_ftm_report_entry_t) * num);

                if (entries) {
                    esp_err_t err = esp_wifi_ftm_get_report(entries, num);
                    if (err == ESP_OK && num > 0) {
                        uint64_t total = 0;
                        for (int i = 0; i < num; i++) {
                            total += entries[i].rtt;
                        }
                        s_rtt_ps = (uint32_t)(total / num);
                        ESP_LOGI(TAG, "FTM OK -- RTT: %"PRIu32" ps  entries: %d",
                                 s_rtt_ps, num);
                    } else {
                        s_rtt_ps = 0;
                    }
                    free(entries);
                }
                xEventGroupSetBits(s_wifi_event_group, FTM_DONE_BIT);
            } else {
                ESP_LOGW(TAG, "FTM failed -- status: %d", report->status);
                xEventGroupSetBits(s_wifi_event_group, FTM_FAILED_BIT);
            }
            break;
        }

        default:
            break;
        }
    } else if (event_base == IP_EVENT && event_id == IP_EVENT_STA_GOT_IP) {
        ip_event_got_ip_t *e = event_data;
        ESP_LOGI(TAG, "STA got IP: " IPSTR, IP2STR(&e->ip_info.ip));
        s_retry_num = 0;
        xEventGroupSetBits(s_wifi_event_group, WIFI_CONNECTED_BIT);
    }
}

// -----------------------------------------------------------------------------
//  MQTT Event Handler
// -----------------------------------------------------------------------------
static void mqtt_event_handler(void *arg, esp_event_base_t event_base,
                                int32_t event_id, void *event_data)
{
    esp_mqtt_event_handle_t event = event_data;

    switch ((esp_mqtt_event_id_t)event_id) {
    case MQTT_EVENT_CONNECTED:
        ESP_LOGI(TAG, "MQTT connected to broker");
        s_mqtt_connected = true;
        break;

    case MQTT_EVENT_DISCONNECTED:
        ESP_LOGW(TAG, "MQTT disconnected");
        s_mqtt_connected = false;
        break;

    case MQTT_EVENT_ERROR:
        ESP_LOGE(TAG, "MQTT error type: %d", event->error_handle->error_type);
        break;

    default:
        break;
    }
}

// -----------------------------------------------------------------------------
//  MQTT Init
// -----------------------------------------------------------------------------
static void mqtt_init(void)
{
    esp_mqtt_client_config_t mqtt_cfg = {
        .broker.uri = MQTT_BROKER_URI,
    };

    s_mqtt_client = esp_mqtt_client_init(&mqtt_cfg);
    esp_mqtt_client_register_event(s_mqtt_client, ESP_EVENT_ANY_ID,
                                   mqtt_event_handler, NULL);
    esp_mqtt_client_start(s_mqtt_client);
    ESP_LOGI(TAG, "MQTT client started -> %s", MQTT_BROKER_URI);
}

// -----------------------------------------------------------------------------
//  Publish raw range measurements as JSON  (one message per anchor)
// -----------------------------------------------------------------------------
static void publish_ranges(void)
{
    if (!s_mqtt_connected || s_mqtt_client == NULL) {
        ESP_LOGW(TAG, "MQTT not connected, skipping publish");
        return;
    }

    // Topic:  capstone/tof/tag/<tag_num>/range
    char topic[80];
    snprintf(topic, sizeof(topic), "%s/%d/range", MQTT_TOPIC_PREFIX, (int)TAG_NUM);

    // Uptime in ms (no RTC, so engine stamps authoritative UTC on arrival)
    int64_t uptime_ms = esp_timer_get_time() / 1000;

    for (int i = 0; i < s_anchor_count; i++) {
        if (!s_anchors[i].valid || !s_anchors[i].ftm_done)
            continue;

        float distance_m = s_anchors[i].distance_cm / 100.0f;

        // RSSI-based confidence heuristic (same scale as anchor firmware)
        float confidence = 1.0f;
        int8_t rssi = s_anchors[i].rssi;
        if (rssi <= -90) {
            confidence = 0.1f;
        } else if (rssi < -50) {
            confidence = 1.0f - ((float)(-50 - rssi) / 40.0f) * 0.9f;
        }

        // Build JSON payload
        char payload[320];
        snprintf(payload, sizeof(payload),
            "{"
            "\"device_id\":\"%s\","
            "\"target_id\":\"anchor_%d\","
            "\"distance_m\":%.3f,"
            "\"rtt_ps\":%"PRIu32","
            "\"rssi\":%d,"
            "\"confidence\":%.2f,"
            "\"scan_number\":%d,"
            "\"uptime_ms\":%lld"
            "}",
            DEVICE_ID,
            s_anchors[i].anchor_id,
            distance_m,
            s_anchors[i].rtt_ps,
            (int)rssi,
            confidence,
            s_scan_number,
            (long long)uptime_ms
        );

        int msg_id = esp_mqtt_client_publish(s_mqtt_client, topic, payload, 0, 1, 0);
        ESP_LOGI(TAG, "MQTT pub [%d] -> %s : %s", msg_id, topic, payload);
    }
}

// -----------------------------------------------------------------------------
//  Wi-Fi Init (AP+STA)
// -----------------------------------------------------------------------------
static void wifi_init_apsta(void)
{
    s_wifi_event_group = xEventGroupCreate();

    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());

    esp_netif_t *ap_netif = esp_netif_create_default_wifi_ap();
    esp_netif_create_default_wifi_sta();

    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&cfg));

    ESP_ERROR_CHECK(esp_event_handler_instance_register(
        WIFI_EVENT, ESP_EVENT_ANY_ID, &wifi_event_handler, NULL, NULL));
    ESP_ERROR_CHECK(esp_event_handler_instance_register(
        IP_EVENT, IP_EVENT_STA_GOT_IP, &wifi_event_handler, NULL, NULL));

    // -- SoftAP config (FTM responder for anchors to range to this tag) --
    wifi_config_t ap_cfg = {
        .ap = {
            .ssid_len       = (uint8_t)strlen(s_tag_ap_ssid),
            .channel        = TAG_AP_CHANNEL,
            .max_connection = TAG_AP_MAX_CONN,
            .authmode       = WIFI_AUTH_OPEN,
            .ftm_responder  = true,
        }
    };
    memcpy(ap_cfg.ap.ssid, s_tag_ap_ssid, strlen(s_tag_ap_ssid));

    // -- STA config --
    wifi_config_t sta_cfg = { 0 };
    strlcpy((char *)sta_cfg.sta.ssid, WIFI_STA_SSID, sizeof(sta_cfg.sta.ssid));
    memset(sta_cfg.sta.password, 0, sizeof(sta_cfg.sta.password));
#if defined(WIFI_STA_PASS) && WIFI_STA_PASS[0] != '\0'
    strlcpy((char *)sta_cfg.sta.password, WIFI_STA_PASS, sizeof(sta_cfg.sta.password));
    sta_cfg.sta.threshold.authmode = WIFI_AUTH_WPA2_PSK;
#else
    sta_cfg.sta.threshold.authmode = WIFI_AUTH_OPEN;
#endif

    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_APSTA));
    ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_AP,  &ap_cfg));
    ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_STA, &sta_cfg));

    // -- Static IP for AP interface --
    ESP_ERROR_CHECK(esp_netif_dhcps_stop(ap_netif));
    esp_netif_ip_info_t ip_info;
    IP4_ADDR(&ip_info.ip,      10, 0, 0, (uint8_t)TAG_AP_IP_LAST);
    IP4_ADDR(&ip_info.gw,      10, 0, 0, (uint8_t)TAG_AP_IP_LAST);
    IP4_ADDR(&ip_info.netmask, 255, 255, 255, 0);
    ESP_ERROR_CHECK(esp_netif_set_ip_info(ap_netif, &ip_info));
    ESP_ERROR_CHECK(esp_netif_dhcps_start(ap_netif));

    ESP_ERROR_CHECK(esp_wifi_start());

    uint8_t mac[6];
    esp_wifi_get_mac(WIFI_IF_AP, mac);
    ESP_LOGI(TAG, "Tag AP: SSID=%s  IP=10.0.0.%d", s_tag_ap_ssid, TAG_AP_IP_LAST);
    ESP_LOGI(TAG, "Tag MAC: %02X:%02X:%02X:%02X:%02X:%02X",
             mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);

    // Wait for STA to connect
    EventBits_t bits = xEventGroupWaitBits(s_wifi_event_group,
                                           WIFI_CONNECTED_BIT | WIFI_FAIL_BIT,
                                           pdFALSE, pdFALSE,
                                           pdMS_TO_TICKS(30000));
    if (bits & WIFI_CONNECTED_BIT) {
        ESP_LOGI(TAG, "STA connected to \"%s\"", WIFI_STA_SSID);
    } else {
        ESP_LOGW(TAG, "STA connection failed -- will retry in background");
    }
}

// -----------------------------------------------------------------------------
//  Scan for TOF_ANCHOR_* SSIDs
// -----------------------------------------------------------------------------
static void scan_for_anchors(void)
{
    s_anchor_count = 0;
    memset(s_anchors, 0, sizeof(s_anchors));

    wifi_scan_config_t scan_cfg = {
        .ssid        = NULL,
        .bssid       = NULL,
        .channel     = 0,
        .show_hidden = false,
        .scan_type   = WIFI_SCAN_TYPE_ACTIVE,
    };

    esp_err_t err = esp_wifi_scan_start(&scan_cfg, true);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "Scan failed: %s", esp_err_to_name(err));
        return;
    }

    uint16_t ap_count = 0;
    esp_wifi_scan_get_ap_num(&ap_count);
    if (ap_count == 0) return;

    wifi_ap_record_t *ap_list = malloc(ap_count * sizeof(wifi_ap_record_t));
    if (!ap_list) return;

    esp_wifi_scan_get_ap_records(&ap_count, ap_list);

    for (int i = 0; i < ap_count && s_anchor_count < MAX_ANCHORS; i++) {
        if (strncmp((char *)ap_list[i].ssid, "TOF_ANCHOR_", 11) != 0) continue;

        // Check FTM responder capability
        if (!ap_list[i].ftm_responder) {
            ESP_LOGW(TAG, "  %s does not support FTM, skipping",
                     (char *)ap_list[i].ssid);
            continue;
        }

        int anchor_id = atoi((char *)ap_list[i].ssid + 11);
        int idx       = s_anchor_count++;

        strlcpy(s_anchors[idx].ssid, (char *)ap_list[i].ssid,
                sizeof(s_anchors[idx].ssid));
        memcpy(s_anchors[idx].bssid, ap_list[i].bssid, 6);
        s_anchors[idx].channel   = ap_list[i].primary;
        s_anchors[idx].anchor_id = anchor_id;
        s_anchors[idx].rssi      = ap_list[i].rssi;
        s_anchors[idx].valid     = true;
        s_anchors[idx].ftm_done  = false;

        ESP_LOGI(TAG, "Found: %s  BSSID: " MACSTR "  CH: %d  RSSI: %d",
                 s_anchors[idx].ssid,
                 MAC2STR(s_anchors[idx].bssid),
                 ap_list[i].primary,
                 ap_list[i].rssi);
    }

    free(ap_list);
    ESP_LOGI(TAG, "Total anchors found: %d", s_anchor_count);
}

// -----------------------------------------------------------------------------
//  Run FTM session to a single anchor
// -----------------------------------------------------------------------------
static bool run_ftm(anchor_info_t *anchor)
{
    xEventGroupClearBits(s_wifi_event_group, FTM_DONE_BIT | FTM_FAILED_BIT);

    wifi_ftm_initiator_cfg_t ftm_cfg = {
        .frm_count    = FTM_FRAME_COUNT,
        .burst_period = FTM_BURST_PERIOD,
        .channel      = anchor->channel,
        .use_get_report_api = true,
    };
    memcpy(ftm_cfg.resp_mac, anchor->bssid, 6);

    esp_err_t err = esp_wifi_ftm_initiate_session(&ftm_cfg);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "FTM initiate failed: %s", esp_err_to_name(err));
        return false;
    }

    EventBits_t bits = xEventGroupWaitBits(s_wifi_event_group,
                                           FTM_DONE_BIT | FTM_FAILED_BIT,
                                           pdTRUE, pdFALSE,
                                           pdMS_TO_TICKS(5000));

    if ((bits & FTM_DONE_BIT) && s_rtt_ps > 0) {
        anchor->rtt_ps      = s_rtt_ps;
        anchor->distance_cm = (s_rtt_ps * 0.03f) / 2.0f;
        anchor->ftm_done    = true;
        ESP_LOGI(TAG, "  %s -> RTT: %"PRIu32" ps  Dist: %.1f cm",
                 anchor->ssid, anchor->rtt_ps, anchor->distance_cm);
        return true;
    }

    return false;
}

// -----------------------------------------------------------------------------
//  Main FTM + publish task  (thin client: scan, range, publish raw data)
// -----------------------------------------------------------------------------
static void ftm_task(void *pvParam)
{
    // Wait for MQTT to be ready
    while (!s_mqtt_connected) {
        ESP_LOGI(TAG, "Waiting for MQTT connection...");
        vTaskDelay(pdMS_TO_TICKS(1000));
    }

    while (true) {
        scan_for_anchors();

        if (s_anchor_count == 0) {
            ESP_LOGW(TAG, "No anchors found, retrying...");
            vTaskDelay(pdMS_TO_TICKS(SCAN_INTERVAL_MS));
            continue;
        }

        s_scan_number++;
        ESP_LOGI(TAG, "======== Scan #%d -- %s ========",
                 s_scan_number, DEVICE_ID);

        // Range to each anchor
        for (int i = 0; i < s_anchor_count; i++) {
            run_ftm(&s_anchors[i]);
            vTaskDelay(pdMS_TO_TICKS(200));
        }

        // Publish raw ranges (no trilateration -- engine handles positioning)
        int ranged = 0;
        for (int i = 0; i < s_anchor_count; i++) {
            if (s_anchors[i].ftm_done) ranged++;
        }

        if (ranged > 0) {
            publish_ranges();
            ESP_LOGI(TAG, "Published %d raw range(s) to engine", ranged);
        } else {
            ESP_LOGW(TAG, "No successful FTM measurements this cycle");
        }

        vTaskDelay(pdMS_TO_TICKS(SCAN_INTERVAL_MS));
    }
}

// -----------------------------------------------------------------------------
//  app_main
// -----------------------------------------------------------------------------
void app_main(void)
{
    snprintf(s_tag_ap_ssid, sizeof(s_tag_ap_ssid), "TOF_TAG_%d", TAG_NUM);

    ESP_LOGI(TAG, "=== FTM Tag %d starting (thin client) ===", TAG_NUM);
    ESP_LOGI(TAG, "    Device:   %s", DEVICE_ID);
    ESP_LOGI(TAG, "    Location: %s / %s", LOCATION_ID, FLOOR_ID);
    ESP_LOGI(TAG, "    Broker:   %s", MQTT_BROKER_URI);
    ESP_LOGI(TAG, "    Topic:    %s/%d/range", MQTT_TOPIC_PREFIX, TAG_NUM);

    // NVS init
    esp_err_t nvs_err = nvs_flash_init();
    if (nvs_err == ESP_ERR_NVS_NO_FREE_PAGES ||
        nvs_err == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_ERROR_CHECK(nvs_flash_erase());
        ESP_ERROR_CHECK(nvs_flash_init());
    }

    // Start Wi-Fi
    wifi_init_apsta();

    // Start MQTT
    mqtt_init();

    // Launch FTM + raw publish task
    vTaskDelay(pdMS_TO_TICKS(1000));
    xTaskCreate(ftm_task, "ftm_task", 8192, NULL, 5, NULL);

    ESP_LOGI(TAG, "Tag %d running (thin) -- SSID \"%s\", MQTT -> %s",
             TAG_NUM, s_tag_ap_ssid, MQTT_BROKER_URI);
}
