// =============================================================================
// anchor_main.c  --  ESP32-S3  Indoor Localization  |  AP+STA Anchor + MQTT
// =============================================================================
//
// This anchor:
//   1. Starts in AP+STA mode (AP for FTM responder, STA for network/MQTT)
//   2. Periodically scans for TOF_TAG_* SSIDs
//   3. Initiates FTM ranging to each discovered tag
//   4. Publishes JSON results to MQTT: capstone/tof/anchor/<anchor_id>/range
//
// JSON payload (one message per tag ranged):
//   {
//     "device_id":   "anchor_4",
//     "target_id":   "tag_0",
//     "distance_m":  2.50,
//     "rtt_ps":      166667,
//     "rssi":        -65,
//     "confidence":  0.85,
//     "scan_number": 42,
//     "uptime_ms":   123456,
//     "anchor_x":    0.0,
//     "anchor_y":    0.0
//   }
//
// =============================================================================

#include <string.h>
#include <stdio.h>
#include <inttypes.h>

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/event_groups.h"
#include "freertos/semphr.h"

#include "esp_system.h"
#include "esp_wifi.h"
#include "esp_event.h"
#include "esp_log.h"
#include "esp_netif.h"
#include "esp_mac.h"
#include "esp_timer.h"
#include "nvs_flash.h"
#include "lwip/ip4_addr.h"
#include "mqtt_client.h"

// -----------------------------------------------------------------------------
//  Per-device config -- auto-generated by platform backend (esp_flash.py)
//  Falls back to defaults if the header does not exist yet.
// -----------------------------------------------------------------------------
#if __has_include("device_config.h")
    #include "device_config.h"
#else
    #warning "device_config.h not found -- using built-in defaults"
    #define ANCHOR_ID           4
    #define ANCHOR_X_CM         0
    #define ANCHOR_Y_CM         0
    #define LOCATION_ID         "building_a"
    #define FLOOR_ID            "floor_1"
    #define WIFI_STA_SSID       "EAP1250"
    #define WIFI_STA_PASS       ""
    #define MQTT_BROKER_URI     "mqtt://192.168.100.10:1883"
    #define AP_CHANNEL          6
#endif

// Fixed settings (same across all anchors)
#define AP_MAX_CONN         4
#define WIFI_RETRY_MAX      5
#define FTM_FRM_COUNT       8
#define FTM_BURST_PERIOD    2
#define SCAN_INTERVAL_MS    2000
#define TAG_SSID_PREFIX     "TOF_TAG_"

// MQTT topic prefix -- matches engine MQTTPipe subscription
#define MQTT_TOPIC_PREFIX   "capstone/tof/anchor"

// -----------------------------------------------------------------------------
//  Globals
// -----------------------------------------------------------------------------
static const char *TAG = "ANCHOR";
static char s_ap_ssid[32];

// Wi-Fi connection
static EventGroupHandle_t s_wifi_event_group;
#define WIFI_CONNECTED_BIT  BIT0
#define WIFI_FAIL_BIT       BIT1
static int s_retry_num = 0;

// MQTT
static esp_mqtt_client_handle_t s_mqtt_client = NULL;
static bool s_mqtt_connected = false;

// FTM
static EventGroupHandle_t s_ftm_event_group;
#define FTM_REPORT_BIT      BIT0
#define FTM_FAILURE_BIT     BIT1
static uint32_t s_ftm_raw_distance_cm = 0;
static SemaphoreHandle_t s_ftm_sem;

// Scan counter
static uint32_t s_scan_number = 0;

// -----------------------------------------------------------------------------
//  Wi-Fi Event Handler
// -----------------------------------------------------------------------------
static void wifi_event_handler(void *arg, esp_event_base_t event_base,
                               int32_t event_id, void *event_data)
{
    if (event_base == WIFI_EVENT) {
        switch (event_id) {

        case WIFI_EVENT_STA_START:
            esp_wifi_connect();
            ESP_LOGI(TAG, "STA started, connecting to %s...", WIFI_STA_SSID);
            break;

        case WIFI_EVENT_STA_DISCONNECTED:
            if (s_retry_num < WIFI_RETRY_MAX) {
                esp_wifi_connect();
                s_retry_num++;
                ESP_LOGW(TAG, "STA disconnected, retry %d/%d",
                         s_retry_num, WIFI_RETRY_MAX);
            } else {
                xEventGroupSetBits(s_wifi_event_group, WIFI_FAIL_BIT);
                ESP_LOGE(TAG, "STA failed after %d retries", WIFI_RETRY_MAX);
            }
            break;

        case WIFI_EVENT_AP_STACONNECTED: {
            wifi_event_ap_staconnected_t *e = event_data;
            ESP_LOGI(TAG, "AP: device " MACSTR " connected", MAC2STR(e->mac));
            break;
        }

        case WIFI_EVENT_AP_STADISCONNECTED: {
            wifi_event_ap_stadisconnected_t *e = event_data;
            ESP_LOGI(TAG, "AP: device " MACSTR " disconnected", MAC2STR(e->mac));
            break;
        }

        default:
            break;
        }
    } else if (event_base == IP_EVENT && event_id == IP_EVENT_STA_GOT_IP) {
        ip_event_got_ip_t *e = event_data;
        ESP_LOGI(TAG, "STA got IP: " IPSTR, IP2STR(&e->ip_info.ip));
        s_retry_num = 0;
        xEventGroupSetBits(s_wifi_event_group, WIFI_CONNECTED_BIT);
    }
}

// -----------------------------------------------------------------------------
//  FTM Event Handler
// -----------------------------------------------------------------------------
static void ftm_event_handler(void *arg, esp_event_base_t event_base,
                               int32_t event_id, void *event_data)
{
    wifi_event_ftm_report_t *report = (wifi_event_ftm_report_t *)event_data;

    if (report->status == FTM_STATUS_SUCCESS) {
        s_ftm_raw_distance_cm = report->dist_est / 100;
        ESP_LOGI(TAG, "FTM: distance=%"PRIu32" cm",
                 s_ftm_raw_distance_cm);
        xEventGroupSetBits(s_ftm_event_group, FTM_REPORT_BIT);
    } else {
        ESP_LOGW(TAG, "FTM: measurement failed (status=%d)", report->status);
        xEventGroupSetBits(s_ftm_event_group, FTM_FAILURE_BIT);
    }
}

// -----------------------------------------------------------------------------
//  MQTT Event Handler
// -----------------------------------------------------------------------------
static void mqtt_event_handler(void *arg, esp_event_base_t event_base,
                                int32_t event_id, void *event_data)
{
    esp_mqtt_event_handle_t event = event_data;

    switch ((esp_mqtt_event_id_t)event_id) {
    case MQTT_EVENT_CONNECTED:
        ESP_LOGI(TAG, "MQTT connected to broker");
        s_mqtt_connected = true;
        break;

    case MQTT_EVENT_DISCONNECTED:
        ESP_LOGW(TAG, "MQTT disconnected");
        s_mqtt_connected = false;
        break;

    case MQTT_EVENT_ERROR:
        ESP_LOGE(TAG, "MQTT error type: %d", event->error_handle->error_type);
        break;

    default:
        break;
    }
}

// -----------------------------------------------------------------------------
//  MQTT Init  (ESP-IDF v6.0 struct layout)
// -----------------------------------------------------------------------------
static void mqtt_init(void)
{
    esp_mqtt_client_config_t mqtt_cfg = {
        .broker = {
            .address = {
                .uri = MQTT_BROKER_URI,
            },
        },
    };

    s_mqtt_client = esp_mqtt_client_init(&mqtt_cfg);
    esp_mqtt_client_register_event(s_mqtt_client, ESP_EVENT_ANY_ID,
                                   mqtt_event_handler, NULL);
    esp_mqtt_client_start(s_mqtt_client);
    ESP_LOGI(TAG, "MQTT client started -> %s", MQTT_BROKER_URI);
}

// -----------------------------------------------------------------------------
//  Publish range measurement as JSON via MQTT
// -----------------------------------------------------------------------------
static void publish_range(const char *tag_id, uint32_t range_cm,
                          int8_t scan_rssi, uint32_t scan_num)
{
    if (!s_mqtt_connected || s_mqtt_client == NULL) {
        ESP_LOGW(TAG, "MQTT not connected, skipping publish");
        return;
    }

    // Topic:  capstone/tof/anchor/<anchor_id>/range
    char topic[80];
    snprintf(topic, sizeof(topic), "%s/%d/range", MQTT_TOPIC_PREFIX, (int)ANCHOR_ID);

    // Uptime in ms
    int64_t uptime_ms = esp_timer_get_time() / 1000;

    float distance_m = range_cm / 100.0f;

    // RSSI-based confidence heuristic
    float confidence = 1.0f;
    if (scan_rssi <= -90) {
        confidence = 0.1f;
    } else if (scan_rssi < -50) {
        confidence = 1.0f - ((float)(-50 - scan_rssi) / 40.0f) * 0.9f;
    }

    // JSON payload
    char payload[384];
    snprintf(payload, sizeof(payload),
        "{"
        "\"device_id\":\"anchor_%d\","
        "\"target_id\":\"tag_%s\","
        "\"distance_m\":%.3f,"
        "\"rtt_ps\":0,"
        "\"rssi\":%d,"
        "\"confidence\":%.2f,"
        "\"scan_number\":%"PRIu32","
        "\"uptime_ms\":%lld,"
        "\"anchor_x\":%.1f,"
        "\"anchor_y\":%.1f"
        "}",
        (int)ANCHOR_ID,
        tag_id,
        distance_m,
        (int)scan_rssi,
        confidence,
        scan_num,
        (long long)uptime_ms,
        (float)ANCHOR_X_CM,
        (float)ANCHOR_Y_CM
    );

    int msg_id = esp_mqtt_client_publish(s_mqtt_client, topic, payload, 0, 1, 0);
    ESP_LOGI(TAG, "MQTT pub [%d] -> %s : %s", msg_id, topic, payload);
}

// -----------------------------------------------------------------------------
//  Initiate FTM to a specific target (by BSSID + channel)
// -----------------------------------------------------------------------------
static bool do_ftm_ranging(const uint8_t *bssid, uint8_t channel)
{
    wifi_ftm_initiator_cfg_t ftm_cfg = {
        .frm_count    = FTM_FRM_COUNT,
        .burst_period = FTM_BURST_PERIOD,
        .channel      = channel,
    };
    memcpy(ftm_cfg.resp_mac, bssid, 6);

    xEventGroupClearBits(s_ftm_event_group, FTM_REPORT_BIT | FTM_FAILURE_BIT);

    esp_err_t err = esp_wifi_ftm_initiate_session(&ftm_cfg);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "FTM initiate failed: %s", esp_err_to_name(err));
        return false;
    }

    EventBits_t bits = xEventGroupWaitBits(s_ftm_event_group,
                                           FTM_REPORT_BIT | FTM_FAILURE_BIT,
                                           pdTRUE, pdFALSE,
                                           pdMS_TO_TICKS(3000));

    return (bits & FTM_REPORT_BIT) != 0;
}

// -----------------------------------------------------------------------------
//  Scan for tags and range to each one
// -----------------------------------------------------------------------------
static void scan_and_range_task(void *pvParams)
{
    // Wait for MQTT to connect before starting
    while (!s_mqtt_connected) {
        ESP_LOGI(TAG, "Waiting for MQTT connection...");
        vTaskDelay(pdMS_TO_TICKS(1000));
    }

    while (true) {
        s_scan_number++;
        ESP_LOGI(TAG, "--- Scan #%"PRIu32" ---", s_scan_number);

        // Active scan for tag APs
        wifi_scan_config_t scan_cfg = {
            .ssid        = NULL,
            .bssid       = NULL,
            .channel     = AP_CHANNEL,
            .show_hidden = true,
            .scan_type   = WIFI_SCAN_TYPE_ACTIVE,
            .scan_time.active.min = 100,
            .scan_time.active.max = 300,
        };

        esp_err_t err = esp_wifi_scan_start(&scan_cfg, true);
        if (err != ESP_OK) {
            ESP_LOGE(TAG, "Scan start failed: %s", esp_err_to_name(err));
            vTaskDelay(pdMS_TO_TICKS(SCAN_INTERVAL_MS));
            continue;
        }

        uint16_t ap_count = 0;
        esp_wifi_scan_get_ap_num(&ap_count);

        if (ap_count == 0) {
            ESP_LOGI(TAG, "No APs found");
            esp_wifi_scan_get_ap_records(&ap_count, NULL);
            vTaskDelay(pdMS_TO_TICKS(SCAN_INTERVAL_MS));
            continue;
        }

        wifi_ap_record_t *ap_records = malloc(sizeof(wifi_ap_record_t) * ap_count);
        if (!ap_records) {
            ESP_LOGE(TAG, "malloc failed for %d AP records", ap_count);
            esp_wifi_scan_get_ap_records(&ap_count, NULL);
            vTaskDelay(pdMS_TO_TICKS(SCAN_INTERVAL_MS));
            continue;
        }

        esp_wifi_scan_get_ap_records(&ap_count, ap_records);

        // Iterate and FTM-range to any TOF_TAG_* SSIDs
        for (int i = 0; i < ap_count; i++) {
            char *ssid = (char *)ap_records[i].ssid;

            if (strncmp(ssid, TAG_SSID_PREFIX, strlen(TAG_SSID_PREFIX)) != 0) {
                continue;
            }

            if (!ap_records[i].ftm_responder) {
                ESP_LOGW(TAG, "  %s does not support FTM, skipping", ssid);
                continue;
            }

            const char *tag_id_str = ssid + strlen(TAG_SSID_PREFIX);
            int8_t scan_rssi = ap_records[i].rssi;

            ESP_LOGI(TAG, "  Ranging to %s [" MACSTR "] CH:%d RSSI:%d",
                     ssid, MAC2STR(ap_records[i].bssid),
                     ap_records[i].primary, scan_rssi);

            if (xSemaphoreTake(s_ftm_sem, pdMS_TO_TICKS(5000)) == pdTRUE) {
                bool ok = do_ftm_ranging(ap_records[i].bssid,
                                         ap_records[i].primary);
                if (ok) {
                    publish_range(tag_id_str, s_ftm_raw_distance_cm,
                                  scan_rssi, s_scan_number);
                }
                xSemaphoreGive(s_ftm_sem);
            } else {
                ESP_LOGW(TAG, "  FTM semaphore timeout, skipping %s", ssid);
            }

            vTaskDelay(pdMS_TO_TICKS(100));
        }

        free(ap_records);
        vTaskDelay(pdMS_TO_TICKS(SCAN_INTERVAL_MS));
    }
}

// -----------------------------------------------------------------------------
//  Wi-Fi Init (AP+STA concurrent mode)
// -----------------------------------------------------------------------------
static void wifi_init_apsta(void)
{
    s_wifi_event_group = xEventGroupCreate();

    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());

    esp_netif_t *ap_netif = esp_netif_create_default_wifi_ap();
    esp_netif_create_default_wifi_sta();

    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&cfg));

    // Wi-Fi events
    ESP_ERROR_CHECK(esp_event_handler_instance_register(
        WIFI_EVENT, ESP_EVENT_ANY_ID, &wifi_event_handler, NULL, NULL));
    ESP_ERROR_CHECK(esp_event_handler_instance_register(
        IP_EVENT, IP_EVENT_STA_GOT_IP, &wifi_event_handler, NULL, NULL));

    // FTM events
    ESP_ERROR_CHECK(esp_event_handler_instance_register(
        WIFI_EVENT, WIFI_EVENT_FTM_REPORT, &ftm_event_handler, NULL, NULL));

    // -- SoftAP config --
    wifi_config_t ap_cfg = {
        .ap = {
            .channel        = AP_CHANNEL,
            .max_connection = AP_MAX_CONN,
            .authmode       = WIFI_AUTH_OPEN,
            .ftm_responder  = true,
        }
    };
    memcpy(ap_cfg.ap.ssid, s_ap_ssid, strlen(s_ap_ssid));
    ap_cfg.ap.ssid_len = (uint8_t)strlen(s_ap_ssid);

    // -- STA config --
    wifi_config_t sta_cfg = { 0 };
    strlcpy((char *)sta_cfg.sta.ssid, WIFI_STA_SSID, sizeof(sta_cfg.sta.ssid));
    memset(sta_cfg.sta.password, 0, sizeof(sta_cfg.sta.password));
#if defined(WIFI_STA_PASS) && WIFI_STA_PASS[0] != '\0'
    strlcpy((char *)sta_cfg.sta.password, WIFI_STA_PASS, sizeof(sta_cfg.sta.password));
    sta_cfg.sta.threshold.authmode = WIFI_AUTH_WPA2_PSK;
#else
    sta_cfg.sta.threshold.authmode = WIFI_AUTH_OPEN;
#endif

    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_APSTA));
    ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_AP,  &ap_cfg));
    ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_STA, &sta_cfg));

    // -- Unique static IP per anchor (AP interface) --
    ESP_ERROR_CHECK(esp_netif_dhcps_stop(ap_netif));

    esp_netif_ip_info_t ip_info;
    IP4_ADDR(&ip_info.ip,      192, 168, 1, (uint8_t)ANCHOR_ID);
    IP4_ADDR(&ip_info.gw,      192, 168, 1, 2);
    IP4_ADDR(&ip_info.netmask, 255, 255, 255, 0);
    ESP_ERROR_CHECK(esp_netif_set_ip_info(ap_netif, &ip_info));
    ESP_ERROR_CHECK(esp_netif_dhcps_start(ap_netif));

    ESP_ERROR_CHECK(esp_wifi_start());

    // -- Static IP on STA interface --
    esp_netif_t *sta_netif = esp_netif_get_handle_from_ifkey("WIFI_STA_DEF");
    esp_netif_dhcpc_stop(sta_netif);

    esp_netif_ip_info_t sta_ip_info;
    IP4_ADDR(&sta_ip_info.ip,      192, 168, 1, (uint8_t)ANCHOR_ID);
    IP4_ADDR(&sta_ip_info.gw,      192, 168, 1, 2);
    IP4_ADDR(&sta_ip_info.netmask, 255, 255, 255, 0);
    esp_netif_set_ip_info(sta_netif, &sta_ip_info);

    ESP_LOGI(TAG, "STA static IP: 192.168.1.%d  GW: 192.168.1.2",
             (int)ANCHOR_ID);

    // Log AP info
    uint8_t mac[6];
    esp_wifi_get_mac(WIFI_IF_AP, mac);
    ESP_LOGI(TAG, "SoftAP started - SSID: %s  CH: %d", s_ap_ssid, AP_CHANNEL);
    ESP_LOGI(TAG, "AP IP:  192.168.1.%d", (int)ANCHOR_ID);
    ESP_LOGI(TAG, "AP MAC: %02X:%02X:%02X:%02X:%02X:%02X",
             mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);

    // Wait for STA connection
    EventBits_t bits = xEventGroupWaitBits(s_wifi_event_group,
                                           WIFI_CONNECTED_BIT | WIFI_FAIL_BIT,
                                           pdFALSE, pdFALSE,
                                           pdMS_TO_TICKS(15000));
    if (bits & WIFI_CONNECTED_BIT) {
        ESP_LOGI(TAG, "STA connected to \"%s\"", WIFI_STA_SSID);
    } else {
        ESP_LOGW(TAG, "STA connection failed - AP still active, MQTT won't work");
    }
}

// -----------------------------------------------------------------------------
//  app_main
// -----------------------------------------------------------------------------
void app_main(void)
{
    snprintf(s_ap_ssid, sizeof(s_ap_ssid), "TOF_ANCHOR_%d", (int)ANCHOR_ID);

    ESP_LOGI(TAG, "=== ToF Anchor %d  [x=%d cm, y=%d cm] ===",
             (int)ANCHOR_ID, ANCHOR_X_CM, ANCHOR_Y_CM);
    ESP_LOGI(TAG, "    Location: %s / %s", LOCATION_ID, FLOOR_ID);
    ESP_LOGI(TAG, "    Broker:   %s", MQTT_BROKER_URI);
    ESP_LOGI(TAG, "    Topic:    %s/%d/range", MQTT_TOPIC_PREFIX, (int)ANCHOR_ID);

    // NVS init
    esp_err_t nvs_err = nvs_flash_init();
    if (nvs_err == ESP_ERR_NVS_NO_FREE_PAGES ||
        nvs_err == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        ESP_ERROR_CHECK(nvs_flash_erase());
        ESP_ERROR_CHECK(nvs_flash_init());
    }

    // FTM sync primitives
    s_ftm_event_group = xEventGroupCreate();
    s_ftm_sem = xSemaphoreCreateMutex();

    // Start Wi-Fi
    wifi_init_apsta();

    // Start MQTT (only useful if STA connected)
    mqtt_init();

    // Launch scan + range task
    xTaskCreatePinnedToCore(scan_and_range_task, "scan_range",
                            8192, NULL, 5, NULL, 0);

    ESP_LOGI(TAG, "Anchor %d running - SSID \"%s\" active, MQTT -> %s",
             (int)ANCHOR_ID, s_ap_ssid, MQTT_BROKER_URI);

    // Keep main task alive
    while (true) {
        vTaskDelay(pdMS_TO_TICKS(10000));
    }
}
