# --- SYSTEM-WIDE CONFIGURATION ---
system:
  localization_method: ""
  frame_window_minutes: 30
  consensus_threshold: 0.80 # Minimmum amount of confidence needed to determine if a device is in a location or not
  signal_filter:
    noise_floor_dbm: -80 # if its bigger than this, its noise and should be ignored
    min_aps_for_localization: 3
  rolling_average_window: 5
  max_distance_for_high_confidence_m: 3.0
  # Replaces magic numbers in trilateration limit logic
  boundary_clamp_margin_m: 0.01

# --- EDGE NODE CONFIGURATION ---
telemetry_config:
  api_ingest_url: "http://10.8.0.1:3000/api/ingest"

  # Poll 10 times per minute (60s / 10 = 6.0s)
  poll_interval_s: 3

  # Aggregate and decide every 1 minute
  update_interval_s: 60

  edge_location_id: "Carleton_University"
  edge_floor_id: "Floor_3"

  # Global defaults to prevent repetition
  default_ap_credentials:
    username: admin
    password: admin

targets:
  - ssid: "NOTHINGPHONE"
    radio_override:
      rssi_at_1m_dbm: -22.0
      path_loss_n: 4.0
  - ssid: "Apple"
    radio_override:
      rssi_at_1m_dbm: -22.0
      path_loss_n: 4.0
  - ssid: "Hphone"
    radio_override:
      rssi_at_1m_dbm: -22.0
      path_loss_n: 4.0

  #- ssid: "SAMSUNGPHONE"
  # radio_override:
  #  rssi_at_1m_dbm: -22.0
  # path_loss_n: 4.0

# --- ENVIRONMENT HIERARCHY AND GEOMETRY ---
locations:
  #Qs_House:
  #floors:
  #Ground_Floor:
  #width_m: 5.47
  #height_m: 5.47

  #aps:
  # APs now inherit 'admin'/'admin' from default_ap_credentials
  # WAP10:
  #  host: 192.168.0.101
  # x: 5.47
  #y: 0.0
  #WAP11:
  # host: 192.168.0.102
  #x: 0.0
  #y: 0.0
  #WAP12:
  # host: 192.168.0.103
  #x: 5.47
  #y: 3.23
  #WAP13:
  # host: 192.168.0.104
  #x: 0.0
  #y: 3.23
  #WAP14:
  # host: 192.168.0.105
  #x: 4.52
  #y: 5.47
  #WAP15:
  # host: 192.168.0.106
  # x: 0.0
  # y: 5.47

  #rooms:
  # Living:
  #  center_x: 2.7
  # center_y: 1.6
  #polygon:
  # - [0.0, 0.0]
  #- [0.0, 3.23]
  #- [5.47, 3.23]
  #- [5.47, 0.0]

  #Kitchen:
  # center_x: 2.2
  # center_y: 4.35
  # polygon:
  #  - [0.0, 3.23]
  #  - [0.0, 5.47]
  #  - [4.52, 5.47]
  # - [4.52, 3.23]

  Carleton_University:
    floors:
      Floor_3:
        width_m: 4.88
        height_m: 3.1

        aps:
          AP31:
            host: 192.168.1.19
            x: 0.0
            y: 0.0
          AP32:
            host: 192.168.1.22
            x: 6.0
            y: 0.0
          AP33:
            host: 192.168.1.54
            x: 0.0
            y: 7.0
          AP34:
            host: 192.168.1.75
            x: 6.0
            y: 7.0
          AP35:
            host: 192.168.1.2
            x: 6.0
            y: 7.0

        rooms:
          472:
            center_x: 2.44
            center_y: 1.55
            polygon:
              - [0.0, 0.0]
              - [6.0, 0.0]
              - [6.0, 7.0]
              - [0.0, 7.0]
